name: Deploy Lambda Function

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: me-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker Image
      run: docker build -t erth-fastapi .

    - name: Tag Docker Image
      run: docker tag erth-fastapi:latest ${{ steps.login-ecr.outputs.registry }}/erth-fastapi:latest

    - name: Push Docker Image to ECR
      run: docker push ${{ steps.login-ecr.outputs.registry }}/erth-fastapi:latest